# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1fa889ae832d122175dbe7bd83fa0a128a2c5c19b6014ed6d2b82284adc5072652763fcc3e144762f1ed528b04f42ea3136c7e58fa4e0c36b9d7c1550a7d57b5

test:
  secret_key_base: 1af76aa19cfba2b5f9fc36082d7767b04924f0bd5c423955be50d2dbbf634b1a2f7596d2ffdfa9511236d8d4da6673c2e3805861341dd65c83f5c0b4af704286

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
